### ISSUE TITLE
ssh 연결 안 됨 (ssh: connect to host AAAA port BBBB: Network is unreachable)

### ISSUE THREAD

**Issue by cozytk** [ainize-team/innoacad-worker-qna#17]
```shell
> ssh innoacad04@AAAA -p BBBB
ssh: connect to host AAAA port BBBB: Network is unreachable
```

**Comment by cozytk** [comment]
아마도 42 서울 교육생에게 제공하는 GPU 대여가 끝나서 제가 사용하던 innoacad04 계정으로도 접속이 불가능한 것 같습니다.
박은종 멘토님께 지속 사용 요청은 드려놓은 상태인데, 월요일 오전중에 멘토님께 다시 한 번 문의 드리겠습니다

**Comment by cozytk** [comment]
```shell
ssh innoacad04@AAAA -p BBBB
innoacad04@AAAA's password:
Last login: Mon Dec 27 13:37:17 2021 from 
Start to Run Container... [PORT_RANGE: 10400-10410]
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Connection to AAAA closed.
```
재접속 시도했는데 네트워크에는 도달한 것 같은데 도커가 실행되지 않는다는 오류 메시지가 나오고 있습니다!

**Comment by minho-comcom-ai** [comment]
@cozytk 밤 사이 그래픽 드라이버의 자동 업데이트가 수행되었고, 이 부분이 docker와 충돌이 나는것을 확인하여, nvidia에 보고 후 rollback하였습니다. 지금 시도해보시면 잘 될 것입니다.

**Comment by cozytk** [comment]
@minho-comcom-ai 잘 실행되는 것 확인했습니다. 감사합니다 :)

**Comment by cozytk** [comment]
```shell
> ssh innoacad04@AAAA -p BBBB
ssh: connect to host AAAA port BBBB: Network is unreachable
```

현재 다시 접속 안됩니다 ㅠㅠ

**Comment by minho-comcom-ai** [comment]
@cozytk 확인해보니, 업데이트 이후, FW도 같이 업데이트 되었는데, 이 FW 업데이트에 수냉 쿨러의 작동기능도 포함되어있는 것 같습니다.
이부분에 문제가 있어 NVIDIA에 문의하였고, NVIDIA와 같이 문제를 파악하여, 현재 장비를 교체해야되는 상황입니다.

**HW교체와 상관없이 바로 개발하실 수 있도록, 다른 HW에 새로 세팅하여드리겠습니다.**

**FYI @all-innoacad-users, 새 HW로 접속하시게되면, 공장초기화 상태의 컨테이너에 접속하시게됩니다. 기존 환경의 백업을 원하시면 계정명을 말해주세요. 감사합니다.**

**Comment by cozytk** [comment]
@minho-comcom-ai
역시 현장에서는 그래픽 업데이트에 따라 트러블슈팅 소요가 많이 발생을 하는군요 ㅠㅠ
개발을 위해서 다른 하드웨어어 세팅 배려해주셔서 감사합니다!
기존 환경 백업 부탁드리고 계정은 cozytk입니다.
